codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "80...100"

  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/jest.config.js"
  - "**/jest.setup.js"
  - "**/__tests__/**"
  - "**/coverage/**"
  - "**/node_modules/**"
  - "**/.next/**"
  - "**/dist/**"